<?php
if ( ! defined( 'ABSPATH' ) && PHP_SAPI !== 'cli' ) { exit; }
class WP_Plugin_Deploy_Abilities {
    private static $services;
    public static function init(){ add_action('wp_abilities_api_categories_init',array(__CLASS__,'register_category')); add_action('wp_abilities_api_init',array(__CLASS__,'register')); }
    public static function register_category(){ if(function_exists('wp_register_ability_category')) wp_register_ability_category('plugin-deployment',array('label'=>__('Plugin Deployment','wp-plugin-deploy'),'description'=>__('Secure installation, update and rollback of WordPress plugins.','wp-plugin-deploy'))); }
    public static function register(){ if(!function_exists('wp_register_ability')) return;
        $common=array('category'=>'plugin-deployment','meta'=>array('public'=>true,'show_in_rest'=>true));
        wp_register_ability('wordpress/plugin-deploy',array_merge($common,array('label'=>__('Deploy WordPress Plugin','wp-plugin-deploy'),'description'=>__('Install or update a plugin from a public GitHub repository or HTTPS ZIP package with backup and rollback.','wp-plugin-deploy'),'input_schema'=>self::deploy_input_schema(),'output_schema'=>array('type'=>'object','additionalProperties'=>true),'execute_callback'=>array(__CLASS__,'execute_deploy'),'permission_callback'=>array(__CLASS__,'can_deploy'),'meta'=>array('public'=>true,'show_in_rest'=>true,'annotations'=>array('readonly'=>false,'destructive'=>true,'idempotent'=>false)))));
        wp_register_ability('wordpress/plugin-rollback',array_merge($common,array('label'=>__('Rollback WordPress Plugin','wp-plugin-deploy'),'description'=>__('Restore a plugin from a deployment backup.','wp-plugin-deploy'),'input_schema'=>array('type'=>'object','properties'=>array('plugin_slug'=>array('type'=>'string'),'backup_id'=>array('type'=>'string')),'required'=>array('plugin_slug'),'additionalProperties'=>false),'output_schema'=>array('type'=>'object','additionalProperties'=>true),'execute_callback'=>array(__CLASS__,'execute_rollback'),'permission_callback'=>array(__CLASS__,'can_rollback'),'meta'=>array('public'=>true,'show_in_rest'=>true,'annotations'=>array('readonly'=>false,'destructive'=>true,'idempotent'=>false)))));
        wp_register_ability('wordpress/plugin-deploy-status',array_merge($common,array('label'=>__('Get Plugin Deployment Status','wp-plugin-deploy'),'description'=>__('Inspect installation, activation, deployment and backup status for a plugin.','wp-plugin-deploy'),'input_schema'=>array('type'=>'object','properties'=>array('plugin_slug'=>array('type'=>'string')),'required'=>array('plugin_slug'),'additionalProperties'=>false),'output_schema'=>array('type'=>'object','additionalProperties'=>true),'execute_callback'=>array(__CLASS__,'execute_status'),'permission_callback'=>array(__CLASS__,'can_status'),'meta'=>array('public'=>true,'show_in_rest'=>true,'annotations'=>array('readonly'=>true,'destructive'=>false,'idempotent'=>true)))));
    }
    private static function deploy_input_schema(){ return array('type'=>'object','properties'=>array('source'=>array('type'=>'string'),'plugin_slug'=>array('type'=>'string'),'ref'=>array('type'=>'string'),'ref_type'=>array('type'=>'string','enum'=>array('branch','tag','release','')),'activate'=>array('type'=>'boolean','default'=>false)),'required'=>array('source'),'additionalProperties'=>false); }
    private static function services(){ if(self::$services)return self::$services; $store=new WP_Plugin_Deploy_Deployment_Store(); $backups=new WP_Plugin_Deploy_Backup_Manager(); $inspector=new WP_Plugin_Deploy_Plugin_Inspector($store,$backups); $rollback=new WP_Plugin_Deploy_Rollback_Manager($backups,$store); $resolver=new WP_Plugin_Deploy_Package_Resolver(); $validator=new WP_Plugin_Deploy_Package_Validator(); $deployer=new WP_Plugin_Deploy_Deployer($resolver,$validator,$backups,$store,$inspector,$rollback); return self::$services=compact('store','backups','inspector','rollback','resolver','validator','deployer'); }
    public static function execute_deploy($input){$s=self::services();return $s['deployer']->deploy((array)$input);}
    public static function execute_rollback($input){$slug=(string)($input['plugin_slug']??''); if(!WP_Plugin_Deploy_Package_Validator::is_valid_slug($slug))return new WP_Error('invalid_plugin_package','Invalid plugin slug.'); $s=self::services();return $s['rollback']->rollback($slug,$input['backup_id']??null);}
    public static function execute_status($input){$slug=(string)($input['plugin_slug']??''); if(!WP_Plugin_Deploy_Package_Validator::is_valid_slug($slug))return new WP_Error('invalid_plugin_package','Invalid plugin slug.'); $s=self::services();return $s['inspector']->status($slug);}
    public static function can_deploy($input){$slug=(string)($input['plugin_slug']??''); if(''!==$slug && !WP_Plugin_Deploy_Package_Validator::is_valid_slug($slug))return false; return $slug && self::services()['inspector']->find_by_slug($slug)?current_user_can('update_plugins'):current_user_can('install_plugins');}
    public static function can_rollback(){return current_user_can('update_plugins');}
    public static function can_status(){return current_user_can('manage_options')||current_user_can('install_plugins')||current_user_can('update_plugins');}
}
